name: Build

on:
  push: 
    branches:
      - main


jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        golang: [1.23]
        terraform: [1.5.5, 1.9.3]
    steps:
      - uses: actions/checkout@v4
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/henrywhitakercommify/golang-terraform:go-${{ matrix.golang }}-tf-${{ matrix.terraform }}
          build-args: |
            GO_VERSION=${{ matrix.golang }}
            TERRAFORM_VERSION=${{ matrix.terraform }}
